### ISSUE TITLE
Very large (and not inline) badges

### ISSUE THREAD

**Issue by Leo40Git** [powercord-community/badges-everywhere#14]
![image](https://user-images.githubusercontent.com/7997354/148639021-6423ac3f-4759-4282-9a62-2d93a8b9474f.png)

Seems like this CSS snippet no longer works as expected:
```css
.badges img {
    width: 100%;
    height: 100%;
}
```

**Comment by george2781** [comment]
I have the same problem.

**Comment by hexa0** [comment]
i'm having the same issue, although i have no idea what i'm doing so i can't fix it, this appears to be because discord renamed a bunch of css stuff in an update

**Comment by zevaryx** [comment]
A temporary (and far from perfect) fix until it's properly fixed is to adjust `style.scss` with the following:
```css
.badges img {
  width: 2%;
  height: 2%;
  display: flex;
  float: left;
}
```
This shrinks them to a more reasonable size, but pushes them to the next line. Better than what's currently happening, but not quite the expected behavior still.
